on:
  push:
    branches:
      - main
    paths:
      - server
      - client
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 16.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: 'Client - npm install, build, and test'
      run: |
        cd client
        npm install
        #npm run test
        npm run build

    - name: 'Server - npm install, build, and test'
      run: |
        cd server
        npm install
        npm test
        npm run build
        cd dist
        npm install --only=production

    - name: 'Run Azure webapp deploy action'
      uses: azure/webapps-deploy@v2
      with:
        app-name: rollagon
        slot-name: staging
        package: ./server/dist