on:
  push:
    branches:
      - main
    paths:
      - infra
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Database Infrastructure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.33.0
        inlineScript: |
          az deployment group create -g database -f ./infra/bicep/main.bicep
