on:
  push:
    branches:
      - main
    paths:
      - server
      - client
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: 'npm install, build, and test'
      run: |
        cd server
        npm install
        #npm run test
        npm run build
        cd dist
        npm install --only=production

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: rollagon
        package: ./server/dist